[package]
name = "tensor_math"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.16"
rand = "0.9.2"
num = "0.4.3"
criterion = "0.7.0"
float-cmp = "0.10.0"

[[bench]]
name = "tensor_benches"
harness = false